version: "3.7"
services:
  ros-core:
    build:
      context: .
      cache_from:
        - ros:melodic-ros-base
      args:
        buildno: 1
    ports:
      - "9090:9090"
      - "11311:11311"
    command:
      - roscore